# Generated by Django 4.0.3 on 2022-04-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=50)),
                ('weight', models.EmailField(max_length=254)),
                ('diet_type', models.CharField(choices=[('Weight loss', 'Weight loss'), ('Weight loss', 'Weight loss'), ('Weight loss', 'Weight loss')], max_length=40)),
            ],
        ),
    ]
