# Generated by Django 4.0.3 on 2022-04-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='diet',
            new_name='dietm',
        ),
    ]
