# Generated by Django 4.0.3 on 2022-04-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
