# Generated by Django 4.0.3 on 2022-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='place',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=250),
        ),
    ]
